In [37]:
import pandas as pd

In [38]:
data=pd.read_csv('Customers.csv')

In [39]:
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [40]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [41]:
print(f' maximo: {data['tenure'].max()}')
print(f' minimo: {data['tenure'].min()}')
print(f' promedio: {data['tenure'].mean()}')

 maximo: 72
 minimo: 0
 promedio: 32.37114865824223

In [42]:
import pandas as pd

data['TotalCharges'] = pd.to_numeric(data['TotalCharges'], errors='coerce')
data['TotalCharges'] = data['TotalCharges'].fillna(data['TotalCharges'].median())

In [43]:

print(f' maximo: {data['TotalCharges'].max()}')
print(f' minimo: {data['TotalCharges'].min()}')
print(f' promedio: {data['TotalCharges'].mean()}')

 maximo: 8684.8
 minimo: 18.8
 promedio: 2281.9169281556156

In [44]:
data['Contract'].value_counts()

Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

In [45]:
data['SeniorCitizen'].value_counts()

SeniorCitizen
0    5901
1    1142
Name: count, dtype: int64

In [46]:
print(data['tenure'].max())
print(data['tenure'].min())
print(data['tenure'].mean())

72
0
32.37114865824223

In [47]:
data.groupby('PaymentMethod')['Churn'].value_counts()

PaymentMethod              Churn
Bank transfer (automatic)  No       1286
                           Yes       258
Credit card (automatic)    No       1290
                           Yes       232
Electronic check           No       1294
                           Yes      1071
Mailed check               No       1304
                           Yes       308
Name: count, dtype: int64

In [48]:
data[data['Churn']=='No']['TotalCharges'].max()

np.float64(8672.45)

In [49]:
data[data['Churn']=='Yes']['TotalCharges'].max()

np.float64(8684.8)

In [50]:
data.groupby('SeniorCitizen')['Churn'].value_counts()

SeniorCitizen  Churn
0              No       4508
               Yes      1393
1              No        666
               Yes       476
Name: count, dtype: int64

In [51]:
dx=data.copy()
dl=data.copy()

In [52]:
cols_dummies=['Contract','PaymentMethod']

In [53]:
for i in cols_dummies:
    dx = pd.get_dummies(dx, columns=[i])

In [54]:
for i in cols_dummies:
    dl = pd.get_dummies(dl, columns=[i])

In [55]:
dx.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,MonthlyCharges,TotalCharges,Churn,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,29.85,29.85,No,True,False,False,False,False,True,False
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,56.95,1889.50,No,False,True,False,False,False,False,True
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,53.85,108.15,Yes,True,False,False,False,False,False,True
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,42.30,1840.75,No,False,True,False,True,False,False,False
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,70.70,151.65,Yes,True,False,False,False,False,True,False

In [56]:
cols1=['SeniorCitizen','tenure','TotalCharges','Contract_Month-to-month','Contract_One year','Contract_Two year','PaymentMethod_Bank transfer (automatic)','PaymentMethod_Credit card (automatic)','PaymentMethod_Electronic check','PaymentMethod_Mailed check']

In [57]:
cols2=['SeniorCitizen','tenure','TotalCharges','Contract_Month-to-month','Contract_One year','Contract_Two year','PaymentMethod_Bank transfer (automatic)','PaymentMethod_Credit card (automatic)','PaymentMethod_Electronic check','PaymentMethod_Mailed check','Churn']

In [58]:
dx=dx[cols1]
dl=dl[cols2]

In [59]:
dx.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 10 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   SeniorCitizen                            7043 non-null   int64
 1   tenure                                   7043 non-null   int64
 2   TotalCharges                             7043 non-null   float64
 3   Contract_Month-to-month                  7043 non-null   bool
 4   Contract_One year                        7043 non-null   bool
 5   Contract_Two year                        7043 non-null   bool
 6   PaymentMethod_Bank transfer (automatic)  7043 non-null   bool
 7   PaymentMethod_Credit card (automatic)    7043 non-null   bool
 8   PaymentMethod_Electronic check           7043 non-null   bool
 9   PaymentMethod_Mailed check               7043 non-null   bool
dtypes: bool(7), float64(1), int64(2)
memory usage: 213.3 KB

In [60]:
dx.head()

,SeniorCitizen,tenure,TotalCharges,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,True,False,False,False,False,True,False
1,0,34,1889.50,False,True,False,False,False,False,True
2,0,2,108.15,True,False,False,False,False,False,True
3,0,45,1840.75,False,True,False,True,False,False,False
4,0,2,151.65,True,False,False,False,False,True,False

In [61]:
# dx['Churn']=dx['Churn'].map({'Yes':1,'No':0})

In [62]:
from sklearn.preprocessing import StandardScaler

In [63]:
scaler = StandardScaler()
dx_scaled = scaler.fit_transform(dx)                                   
dx = pd.DataFrame(dx_scaled, columns=dx.columns, index=dx.index)

In [64]:
from sklearn.cluster import KMeans

modelo = KMeans(n_clusters=2, random_state=42)
modelo.fit(dx)

KMeans(n_clusters=2, random_state=42)

In [65]:
dl['Cluster']=modelo.fit_predict(dx)

In [66]:
dl['Cluster']=modelo.labels_

In [67]:
dl['Cluster'].value_counts()

Cluster
1    3812
0    3231
Name: count, dtype: int64

In [68]:
dl[dl['tenure']>32]['Cluster'].value_counts()

Cluster
0    2561
1     707
Name: count, dtype: int64

In [69]:
dl[dl['tenure']<32]['Cluster'].value_counts()

Cluster
1    3059
0     647
Name: count, dtype: int64

In [70]:
dl.head()

,SeniorCitizen,tenure,TotalCharges,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn,Cluster
0,0,1,29.85,True,False,False,False,False,True,False,No,1
1,0,34,1889.50,False,True,False,False,False,False,True,No,0
2,0,2,108.15,True,False,False,False,False,False,True,Yes,1
3,0,45,1840.75,False,True,False,True,False,False,False,No,0
4,0,2,151.65,True,False,False,False,False,True,False,Yes,1

In [71]:
dl.groupby('Churn')['Cluster'].value_counts()

Churn  Cluster
No     0          3006
       1          2168
Yes    1          1644
       0           225
Name: count, dtype: int64

In [72]:
print(dl['TotalCharges'].mean())

2281.9169281556156

In [73]:
dl[dl['TotalCharges']>2300]['Cluster'].value_counts()

Cluster
0    1873
1     762
Name: count, dtype: int64

In [74]:
dl[dl['TotalCharges']<2300]['Cluster'].value_counts()

Cluster
1    3050
0    1358
Name: count, dtype: int64

In [75]:
dl['Contract_Month-to-month'].unique()

array([ True, False])

In [76]:
dl[dl['Contract_Month-to-month']==1]['Cluster'].value_counts()

Cluster
1    3788
0      87
Name: count, dtype: int64

In [77]:
dl[dl['Contract_Month-to-month']==0]['Cluster'].value_counts()

Cluster
0    3144
1      24
Name: count, dtype: int64

In [78]:
dl[dl['Contract_One year']==0]['Cluster'].value_counts()

Cluster
1    3789
0    1781
Name: count, dtype: int64

In [79]:
dl[dl['Contract_One year']==1]['Cluster'].value_counts()

Cluster
0    1450
1      23
Name: count, dtype: int64

In [80]:
dl[dl['Contract_Two year']==1]['Cluster'].value_counts()

Cluster
0    1694
1       1
Name: count, dtype: int64

In [81]:
dl[dl['Contract_Two year']==0]['Cluster'].value_counts()

Cluster
1    3811
0    1537
Name: count, dtype: int64

In [82]:
dl.groupby('Cluster')['tenure'].mean()

Cluster
0    50.520582
1    16.987933
Name: tenure, dtype: float64

In [83]:
dl.groupby('Cluster')['TotalCharges'].mean()

Cluster
0    3486.132289
1    1261.240163
Name: TotalCharges, dtype: float64

In [84]:
dl.groupby("Cluster")[["tenure","TotalCharges"]].mean()

            tenure  TotalCharges
Cluster
0        50.520582   3486.132289
1        16.987933   1261.240163

In [85]:
contract_cols = [
    "Contract_Month-to-month",
    "Contract_One year",
    "Contract_Two year"
]

dl.groupby("Cluster")[contract_cols].mean() * 100

         Contract_Month-to-month  Contract_One year  Contract_Two year
Cluster
0                       2.692665          44.877747          52.429588
1                      99.370409           0.603358           0.026233

## RECOMENDACIONES

### 1. Estrategia de fidelización
Los clientes con mayor antigüedad y contratos de uno o dos años presentan una mayor estabilidad y representan el segmento de mayor valor para la empresa. En contraste, los clientes con contratos mensuales y menor tiempo de permanencia muestran un comportamiento más inestable y requieren estrategias de retención.

### 2. Automatización de campañas
Implementar campañas automatizadas mediante herramientas como Make o n8n para enviar promociones, descuentos y recordatorios personalizados por correo electrónico o WhatsApp a los clientes con mayor riesgo de abandono. En casos específicos, el sistema puede derivar al cliente a un asesor humano para brindar atención personalizada.

### 3. Asistente basado en IA generativa
Integrar un asistente utilizando modelos de lenguaje como OpenAI, Claude o modelos open source que analice la información del cliente y genere explicaciones en lenguaje natural sobre su nivel de estabilidad, los factores que influyen en su comportamiento y recomendaciones para mejorar su retención.

### 4. Desarrollo de una aplicación
Desarrollar una aplicación web donde usuarios no técnicos puedan ingresar la información de un cliente y obtener automáticamente:
- El segmento al que pertenece.
- Una estimación de su nivel de estabilidad.
- Recomendaciones de retención.
- Explicaciones generadas por IA para facilitar la toma de decisiones.

### 5. Priorización de clientes

No todos los clientes requieren las mismas acciones de retención. Se recomienda priorizar las campañas sobre aquellos segmentos con mayor riesgo de abandono y mayor valor económico, optimizando así los recursos destinados a marketing y atención al cliente.